export const images = {
  Menu: require('../Images/Menu.png'),
  Notify: require('../Images/Notif.png'),
  Star: require('../Images/Star.png'),
  Search: require('../Images/Search.png'),
  cinema: require('../Images/cinema.png'),
  tickit: require('../Images/tickit.png'),
  bookmark: require('../Images/bookmark.png'),
  back: require('../Images/back.png'),
  clock: require('../Images/clock.png'),
  user1: require('../Images/user1.png'),
  user2: require('../Images/user2.png'),
  user3: require('../Images/user3.png'),
  user4: require('../Images/user4.png'),
};
